version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PROXY_HOST=http://backend:8000
    volumes:
      - ./frontend:/home/app/
      - /home/app/node_modules

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/home/app/
      - /home/app/venv
